name: Set up Java 17

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # Specifies Java 17
          distribution: 'temurin'    # Specifies the JDK distribution (Temurin is a popular choice)

      # Step 3: Set up Maven (if needed)
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # Ensure that Maven uses Java 17
          distribution: 'temurin'
          maven-version: '3.8.1'    # Optional: Specify a specific Maven version, e.g., 3.8.1

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn clean
