name: Build and Test Swagger Project

# Controla cuándo se ejecutará el flujo de trabajo.
on:
  push:
    branches:
      - main  # o la rama que desees que active el flujo de trabajo.
  pull_request:
    branches:
      - main  # o la rama que desees.

jobs:
  build:
    runs-on: ubuntu-latest  # El flujo de trabajo se ejecutará en un contenedor Ubuntu.

    steps:
      # Paso 1: Checkout el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Paso 3: Instalar dependencias y compilar el proyecto
      - name: Build with Maven
        run: mvn clean install -f target/pom.xml 


      # Paso 5: (Opcional) Desplegar el artefacto si todo sale bien
      - name: Deploy (Ejemplo)
        run: |
          echo "Desplegando artefacto"
          # Aquí agregarías los pasos para desplegar tu artefacto si fuera necesario.
