name: Build and Test Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar JDK 11 (si es necesario)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Especifica la distribución si es necesario

      # Paso 3: Ejecutar la construcción
      - name: Build with Maven
        run: mvn clean install -f target/pom.xml

      # Paso 4: Ejecutar pruebas
      - name: Run Tests
        run: mvn test -f target/pom.xml
