name: Clean Maven Project

on:
  push:
    branches:
      - main  # Se ejecuta cuando se hace push a la rama `main`
  pull_request:
    branches:
      - main  # Se ejecuta cuando se hace un PR hacia la rama `main`

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # Specifies Java 17
          distribution: 'temurin'    # Specifies the JDK distribution (Temurin is a popular choice)

      # Step 3: Set up Maven (if needed)
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # Ensure that Maven uses Java 17
          distribution: 'temurin'
          maven-version: '3.8.1'    # Optional: Specify a specific Maven version, e.g., 3.8.1

      - name: Clean project with Maven
        run: mvn -f ./Swagger/pom.xml clean package -DskipTests  # Cambia a la ruta del pom.xml en tu proyecto 

      - name: Run tests
        run: mvn test  # Si quieres ejecutar las pruebas también, puedes añadir este paso

      - name: Upload Build Artifacts (Opcional)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: my-build-artifacts
          path: target/*.jar  # O el 
