name: Set up Java 17

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # Specifies Java 17
          distribution: 'temurin'    # Specifies the JDK distribution (Temurin is a popular choice)

      # Step 3: Set up Maven (if needed)
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # Ensure that Maven uses Java 17
          distribution: 'temurin'
          maven-version: '3.8.1'    # Optional: Specify a specific Maven version, e.g., 3.8.1

      - name: Verify pom.xml exists
        run: |
          if [ ! -f pom.xml ]; then
            echo "Error: pom.xml not found in the current directory."
            exit 1
          fi
          cat pom.xml  # Imprimir el contenido de pom.xml como verificación

      # Paso 4: Ejecutar `mvn clean`
      - name: Clean project with Maven
        run: mvn clean  # Ejecuta mvn clean para limpiar el proyecto
